<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // DB::table('provinces')->insert([
        //     [
        //         'name' => 'BUBANZA',
        //         'slug' => 'bubanza',
        //         'description' => null,
        //         'province_latitude' => '-3.08459',
        //         'province_longitude' => '29.3948',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'BUJUMBURA',
        //         'slug' => 'bujumbura',
        //         'description' => null,
        //         'province_latitude' => '-3.34607',
        //         'province_longitude' => '29.4835',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'BUJUMBURA MAIRIE',
        //         'slug' => 'bujumbura-mairie',
        //         'description' => null,
        //         'province_latitude' => '-3.3931005',
        //         'province_longitude' => '29.3690935',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'BURURI',
        //         'slug' => 'bururi',
        //         'description' => null,
        //         'province_latitude' => '-3.94794',
        //         'province_longitude' => '29.6169',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'CANKUZO',
        //         'slug' => 'cankuzo',
        //         'description' => null,
        //         'province_latitude' => '-3.14362',
        //         'province_longitude' => '30.2973',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'CIBITOKE',
        //         'slug' => 'cibitoke',
        //         'description' => null,
        //         'province_latitude' => '-2.84977',
        //         'province_longitude' => '28.9592',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'GITEGA',
        //         'slug' => 'gitega',
        //         'description' => null,
        //         'province_latitude' => '-3.43143',
        //         'province_longitude' => '29.9079',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'KARUSI',
        //         'slug' => 'karusi',
        //         'description' => null,
        //         'province_latitude' => '-3.14937',
        //         'province_longitude' => '29.8351',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'KAYANZA',
        //         'slug' => 'kayanza',
        //         'description' => null,
        //         'province_latitude' => '-3.01417',
        //         'province_longitude' => '29.3533',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'KIRUNDO',
        //         'slug' => 'kirundo',
        //         'description' => null,
        //         'province_latitude' => '-2.55596',
        //         'province_longitude' => '29.8933',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'MAKAMBA',
        //         'slug' => 'makamba',
        //         'description' => null,
        //         'province_latitude' => '-4.20607',
        //         'province_longitude' => '29.5075',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'MURAMVYA',
        //         'slug' => 'muramvya',
        //         'description' => null,
        //         'province_latitude' => '-3.26797',
        //         'province_longitude' => '29.6152',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'MUYINGA',
        //         'slug' => 'muyinga',
        //         'description' => null,
        //         'province_latitude' => '-2.84551',
        //         'province_longitude' => '30.3337',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'MWARO',
        //         'slug' => 'mwar',
        //         'description' => null,
        //         'province_latitude' => '-3.51254',
        //         'province_longitude' => '29.693',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'NGOZI',
        //         'slug' => 'ngozi',
        //         'description' => null,
        //         'province_latitude' => '-2.90847',
        //         'province_longitude' => '29.8057',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'RUMONGE',
        //         'slug' => 'rumonge',
        //         'description' => null,
        //         'province_latitude' => '-3.97226',
        //         'province_longitude' => '29.4305',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'RUTANA',
        //         'slug' => 'rutana',
        //         'description' => null,
        //         'province_latitude' => '-3.92546',
        //         'province_longitude' => '29.9823',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => null,
        //     ],
        //     [
        //         'name' => 'RUYIGI',
        //         'slug' => 'ruyigi',
        //         'description' => null,
        //         'province_latitude' => '-3.47421',
        //         'province_longitude' => '30.2379',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => '2024-11-03 14:47:07',
        //     ],
        //     [
        //         'name' => 'SUD-KIVU',
        //         'slug' => 'sud-kivu',
        //         'description' => null,
        //         'province_latitude' => '-3.206704336023286',
        //         'province_longitude' => '29.07004647884585',
        //         'pays_code' => 'CD',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => '2024-11-03 14:47:02',
        //     ],
        //     [
        //         'name' => 'NORD-KIVU',
        //         'slug' => 'nord-kivu',
        //         'description' => null,
        //         'province_latitude' => '-1.6607633259896675',
        //         'province_longitude' => '29.20248976118807',
        //         'pays_code' => 'CD',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => '2024-11-03 14:46:58',
        //     ],
        //     [
        //         'name' => 'KAGERA',
        //         'slug' => 'kagera',
        //         'description' => null,
        //         'province_latitude' => '-1.582287825208144',
        //         'province_longitude' => '31.042743719598118',
        //         'pays_code' => 'TZ',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => '2024-11-03 14:46:54',
        //     ],
        //     [
        //         'name' => 'BUJUMBURA RURAL',
        //         'slug' => 'bujumbura-rural',
        //         'description' => null,
        //         'province_latitude' => '-3.4190434767517357',
        //         'province_longitude' => '29.384908676147464',
        //         'pays_code' => 'BI',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => '2024-11-03 14:48:20',
        //     ],
        //     [
        //         'name' => 'REGION DAKAR',
        //         'slug' => 'region-dakar',
        //         'description' => null,
        //         'province_latitude' => '14.720094792437695',
        //         'province_longitude' => '-17.465235383193246',
        //         'pays_code' => 'SN',
        //         'country_id' => null,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //         'deleted_at' => '2024-11-03 14:46:37',
        //     ],
        // ]);
        DB::table('provinces')->insert([
            [
                'id' => 1,
                'name' => 'BUHUMUZA',
                'slug' => Str::slug('BUHUMUZA'),
                'description' => null,
                'province_latitude' => null,
                'province_longitude' => null,
                'pays_code' => null,
                'country_id' => null,
                'created_at' => '2024-07-18 20:49:07',
                'updated_at' => '2024-07-18 20:49:07',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'BUJUMBURA',
                'slug' => Str::slug('BUJUMBURA'),
                'description' => null,
                'province_latitude' => null,
                'province_longitude' => null,
                'pays_code' => null,
                'country_id' => null,
                'created_at' => '2024-07-18 20:49:07',
                'updated_at' => '2024-07-18 20:49:07',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'BURUNGA',
                'slug' => Str::slug('BURUNGA'),
                'description' => null,
                'province_latitude' => null,
                'province_longitude' => null,
                'pays_code' => null,
                'country_id' => null,
                'created_at' => '2024-07-18 20:49:07',
                'updated_at' => '2024-07-18 20:49:07',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'BUTANYERERA',
                'slug' => Str::slug('BUTANYERERA'),
                'description' => null,
                'province_latitude' => null,
                'province_longitude' => null,
                'pays_code' => null,
                'country_id' => null,
                'created_at' => '2024-07-18 20:49:07',
                'updated_at' => '2024-07-18 20:49:07',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'GITEGA',
                'slug' => Str::slug('GITEGA'),
                'description' => null,
                'province_latitude' => null,
                'province_longitude' => null,
                'pays_code' => null,
                'country_id' => null,
                'created_at' => '2024-07-18 20:49:07',
                'updated_at' => '2024-07-18 20:49:07',
                'deleted_at' => null,
            ]
        ]);
    }
}
